# Generated by Django 3.2.7 on 2021-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('name', models.TextField()),
                ('salary', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
