# Generated by Django 3.2.7 on 2021-09-05 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator('0.0', message='Salary cannot be negative')]),
        ),
    ]
